/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.23.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package microarch.delivery.adapters.in.http.api;

import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import microarch.delivery.adapters.in.http.model.CreateCourierResponse;
import microarch.delivery.adapters.in.http.model.Error;
import microarch.delivery.adapters.in.http.model.NewCourier;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-07-18T18:31:02.352874400+03:00[Europe/Moscow]", comments = "Generator version: 7.23.0")
@Validated
@Tag(name = "CreateCourier", description = "the CreateCourier API")
public interface CreateCourierApi {

    String PATH_CREATE_COURIER = "/api/v1/couriers";
    /**
     * POST /api/v1/couriers : Добавить курьера
     * Позволяет добавить курьера
     *
     * @param newCourier Курьер (required)
     * @return Курьер успешно создан (status code 201)
     *         or Некорректные параметры запроса (status code 400)
     *         or Конфликт при создании курьера (status code 409)
     *         or Внутренняя ошибка сервиса (status code 500)
     */
    @Operation(
        operationId = "createCourier",
        summary = "Добавить курьера",
        description = "Позволяет добавить курьера",
        tags = { "CreateCourier" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Курьер успешно создан", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CreateCourierResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "Некорректные параметры запроса", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "409", description = "Конфликт при создании курьера", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Внутренняя ошибка сервиса", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = CreateCourierApi.PATH_CREATE_COURIER,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    ResponseEntity<CreateCourierResponse> createCourier(
        @Parameter(name = "NewCourier", description = "Курьер", required = true) @Valid @RequestBody NewCourier newCourier
    );

}
