/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.23.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package microarch.delivery.adapters.in.http.api;

import model.CreateOrderResponse;
import model.Error;
import model.NewOrder;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-07-18T18:31:02.352874400+03:00[Europe/Moscow]", comments = "Generator version: 7.23.0")
@Validated
@Tag(name = "CreateOrder", description = "the CreateOrder API")
public interface CreateOrderApi {

    String PATH_CREATE_ORDER = "/api/v1/orders";
    /**
     * POST /api/v1/orders : Создать заказ
     * Позволяет создать заказ с целью тестирования
     *
     * @param newOrder Новый заказ (required)
     * @return Заказ успешно создан (status code 201)
     *         or Некорректные параметры запроса (status code 400)
     *         or Конфликт при создании заказа (status code 409)
     *         or Внутренняя ошибка сервиса (status code 500)
     */
    @Operation(
        operationId = "createOrder",
        summary = "Создать заказ",
        description = "Позволяет создать заказ с целью тестирования",
        tags = { "CreateOrder" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Заказ успешно создан", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = CreateOrderResponse.class))
            }),
            @ApiResponse(responseCode = "400", description = "Некорректные параметры запроса", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "409", description = "Конфликт при создании заказа", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            }),
            @ApiResponse(responseCode = "500", description = "Внутренняя ошибка сервиса", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = CreateOrderApi.PATH_CREATE_ORDER,
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    ResponseEntity<CreateOrderResponse> createOrder(
        @Parameter(name = "NewOrder", description = "Новый заказ", required = true) @Valid @RequestBody NewOrder newOrder
    );

}
