/*
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.23.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package microarch.delivery.adapters.in.http.api;

import microarch.delivery.adapters.in.http.model.Error;
import microarch.delivery.adapters.in.http.model.Location;
import java.util.UUID;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ExampleObject;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.multipart.MultipartFile;

import jakarta.validation.Valid;
import jakarta.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;
import jakarta.annotation.Generated;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2026-07-18T18:31:02.352874400+03:00[Europe/Moscow]", comments = "Generator version: 7.23.0")
@Validated
@Tag(name = "MoveCourier", description = "the MoveCourier API")
public interface MoveCourierApi {

    String PATH_MOVE_COURIER = "/api/v1/couriers/{courierId}/move";

    /**
     * POST /api/v1/couriers/{courierId}/move : Переместить курьера Позволяет переместить курьера
     *
     * @param courierId
     *            Идентификатор курьера (required)
     * @param location
     *            Местоположение (required)
     *
     * @return Успешный ответ (status code 200) or Некорректные параметры запроса (status code 400) or Конфликт при
     *         перемещении курьера (status code 409) or Внутренняя ошибка сервиса (status code 500)
     */
    @Operation(operationId = "moveCourier", summary = "Переместить курьера", description = "Позволяет переместить курьера", tags = {
            "MoveCourier" }, responses = { @ApiResponse(responseCode = "200", description = "Успешный ответ"),
                    @ApiResponse(responseCode = "400", description = "Некорректные параметры запроса", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class)) }),
                    @ApiResponse(responseCode = "409", description = "Конфликт при перемещении курьера", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class)) }),
                    @ApiResponse(responseCode = "500", description = "Внутренняя ошибка сервиса", content = {
                            @Content(mediaType = "application/json", schema = @Schema(implementation = Error.class)) }) })
    @RequestMapping(method = RequestMethod.POST, value = MoveCourierApi.PATH_MOVE_COURIER, produces = {
            "application/json" }, consumes = { "application/json" })
    ResponseEntity<Void> moveCourier(
            @Parameter(name = "courierId", description = "Идентификатор курьера", required = true, in = ParameterIn.PATH) @PathVariable("courierId") UUID courierId,
            @Parameter(name = "Location", description = "Местоположение", required = true) @Valid @RequestBody Location location);

}
